cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Detalle.as_view(), name="cart_detail"),
    url(r'^add/(?P<producto_id>\d+)/$', views.Agregar.as_view(), name="cart_add"),
    url(r'^remove/(?P<producto_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.Home.as_view(), name="home"),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^create/$',views.CreateOrder.as_view(), name="create"),
]	

payment/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^process/$', views.PaymentProcess.as_view(),name='process'),
	url(r'^done/$',	views.payment_done, name="done"),
	url(r'^canceled/$',	views.payment_canceled,	name="canceled"),
]

soporte/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from tienda import urls as tiendaUrls
from cart import urls as cartUrls
from orders import urls as orderUrls
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls
from main import urls as UrlsMain
#for socialauth
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

SOCIAL_AUTH_URL_NAMESPACE = 'social'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(UrlsMain,namespace="home")),
    url(r'^tienda/', include(tiendaUrls, namespace="tienda")),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs ={'document_root':settings.MEDIA_ROOT}
        ),

url(r'^orders/', include(orderUrls, namespace="orders")),
    url(r'^paypal/', include(paypalUrls)),
    url(r'^payment/', include(paymentUrls,namespace='payment')),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL
    url(
        r'^users/logout/$',
        logout,
        {'next_page': '/products'},
        name="user-logout"),
]

tienda/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Lista.as_view(), name="tienda"),
    url(r'^(?P<producto_id>\d+)/$', views.Detalle.as_view(), name="detalle"),
]

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from tienda.models import Producto

class Order(models.Model):
	first_name = models.CharField(max_length=140)
	last_name = models.CharField(max_length=140)
	email = models.EmailField()
	fecha = models.DateTimeField(auto_now_add=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-fecha',)

	def __str__(self):
		return 'Orden {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items')
	producto = models.ForeignKey(Producto, related_name='order_items')
	precio = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.precio*self.quantity

payment/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

class Producto(models.Model):
    imagen = models.FileField(upload_to='tienda/%Y/%m/%d/', null=True, blank=True)
    nombre = models.CharField(max_length=140)
    precio = models.FloatField()

cart/forms.py
from django import forms

CHOICES = ((i,str(i)) for i in range(1,21))

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=CHOICES, coerce=int)
	update = forms.BooleanField(required=False,initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
	class Meta:
		model =Order
		fields =[
			'first_name','last_name','email']

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CartAddProductForm
from django.views.generic import View
from .cart import Cart
from tienda.models import Producto

class Agregar(View):
	def post(self,request,producto_id):
		cart = Cart(request)
		producto = get_object_or_404(Producto,id=producto_id)
		form = CartAddProductForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			cart.add(producto=producto,
				quantity=cd['quantity'],
				update_quantity=cd['update'])
		return redirect('tienda:tienda')

class Remove(View):
	def get(self,request,producto_id):
		cart = Cart(request)
		producto = get_object_or_404(Producto,id=producto_id)
		cart.remove(producto)
		return redirect('cart:cart_detail')

class Detalle(View):
	def get(self,request):
		cart = Cart(request)
		return render(request,'cart/detalle.html',{'cart':cart})

main/views.py
from django.shortcuts import render
from django.views.generic import View

class Home(View):
	def get(self, request):
		template_name= 'home.html'
		return render(request, template_name)

orders/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic import View
from .forms import OrderCreateForm
from cart.cart import Cart
from .models import OrderItem, Order
from .tasks import order_created

class CreateOrder(View):
	def get(delf, request):
		form = OrderCreateForm()
		template_name = 'orders/create.html'
		context = {
		'form':form,
		'cart':Cart(request)
		}
		return render(request, template_name, context)

	def post(self, request):
		cart = Cart(request)
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			order = form.save()
			for item in cart:
				OrderItem.objects.create(
					order=order,
					producto=item['producto'],
					precio=item['precio'],
					quantity=item['quantity']
					)
			#borrar carrito
			cart.clear()
			#enviaremos una tarea asincrona a celery
			#order_created.delay(order.id)

			#orden para paypal
			request.session['order_id']=order.id
			return redirect(reverse('payment:process'))
		else:
			cart=Cart(request)
			form=OrderCreateForm(request.POST)
			template='orders/create.html'
			context={
			'cart':cart,
			'form':form
			}
		return render(request,template,context)

payment/views.py
from django.shortcuts import render
from decimal import Decimal
from django.conf import settings
from django.core.urlresolvers import reverse
from django.shortcuts import render,get_object_or_404
from paypal.standard.forms import PayPalPaymentsForm
from orders.models import Order
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt

class PaymentProcess(View):
	def get(self,request):
		order_id=request.session.get('order_id')
		order=get_object_or_404(Order,id=order_id)
		host=request.get_host()

		paypal_dict={
			'business':settings.PAYPAL_RECEIVER_EMAIL,
			'amount':'%.2f' % order.get_total_cost().quantize(Decimal('.01')),
			'item_name':'Order {}'.format(order.id),
			'invoice':str(order.id),
			'currency_code':'MXN',
			'notify_url':'http://{}{}'.format(host,reverse('paypal-ipn')),
			'return_url':'http://{}{}'.format(host,reverse('payment:done')),
			'cancel_return':'http://{}{}'.format(host,reverse('payment:canceled')),
		}
		form=PayPalPaymentsForm(initial=paypal_dict)
		return render(request,'payment/process.html',{'order':order,'form':form})

@csrf_exempt
def payment_done(request):
	order_id=request.session.get('order_id')
	order=get_object_or_404(Order,id=order_id)
	order.paid = True
	order.save()
	return render(request,'payment/done.html')

@csrf_exempt
def payment_canceled(request):
	return render(request,'payment/canceled.html')

tienda/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Producto
from cart.forms import CartAddProductForm

class Lista(View):
    def get(self, request):
        productos = Producto.objects.all()
        template_name = 'tienda/lista.html'
        context = {
        'productos':productos
        }
        return render(request, template_name, context)

class Detalle(View):
    def get(self, request, producto_id):
        template_name = 'tienda/detalle.html'
        producto = get_object_or_404(Producto,id=producto_id)
        form = CartAddProductForm()
        context = {
        'producto':producto,
        'form':form
        }
        return render(request, template_name, context)

cart/templates/cart/detalle.html
{% extends 'base.html'%} {% block content%}
<html>

<head>
    <meta charset="utf-8">
    <title>Carrito</title>
    <meta charset="utf-8">
</head>

<body>
    <div id="wrapper" , class="center">
        <br></br>
        <h1 class="center">Tu carrito</h1>
        <table>
            <thead>
                <tr>
                    <th>Imagen</th>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Quitar</th>
                    <th>Precio Unitario</th>
                    <th>SubTotal</th>
                </tr>
            </thead>
            <tbody>
                {%for item in cart%} {%with producto=item.producto%}
                <tr>
                    <td>
                        <img src="/media/{{producto.imagen}}" height="100">
                    </td>
                    <td>
                        {{producto.nombre}}
                    </td>
                    <td>
                        {{item.quantity}}
                    </td>
                    <td>
                        <a href="{%url 'cart:cart_remove' producto.id%}">Quitar</a>
                    </td>
                    <td>
                        $ {{item.precio}}
                    </td>
                    <td>
                        $ {{item.precio_total}}
                    </td>
                </tr>
                {%endwith%} {%endfor%}
                <tr>
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td>$ {{cart.get_precio_total}}</td>
                </tr>
            </tbody>
        </table>
        <form action="{%url 'tienda:tienda'%}">
            <input type="submit" value="Seguir Comprando">
        </form>
        <form action="{%url 'orders:create'%}">
                <input type="submit" value="Pagar">
        </form>
    </div>
</body>

</html>
{% endblock content%}

main/templates/base.html
{%load static%}

<html>

<head>
	<title>
		{%block titulo%} Soporte Técnico 24hrs {%endblock titulo%}
	</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--Import Google Icon Font-->
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
	<!--Import Google Icon Font-->
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	<link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" /> {%block head%} {%endblock head%}
</head>

<body>

	<!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="js/materialize.min.js"></script>

	<nav class="blue darken-4 navbar-fixed">

		<div class="nav-wrapper">
			<a href="{%url 'home:home'%}" class="brand-logo">Soporte Técnico en computadoras</a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><a href="{%url 'home:home'%}">Inicio</a></li>
				<li><a href="#">Acerca</a></li>
				<li><a href="#">Iniciar Sesión</a></li>
				<li><a href="#">Registrate</a></li>
				<li><a href="{%url 'tienda:tienda'%}">Tienda</a></li>
				<li><a href="{%url 'cart:cart_detail'%}">
				{%with total_items=cart|length%}<img src="/media/tienda/carrito.png {{producto.imegen}}" height="20">
				{{total_items}} {%if total_items > 0%}
			 	{{total_items|pluralize}}
			  {%else%} {{tota_items}} {%endif%}{%endwith%}</a></li>
			</ul>
		</div>
	</nav>

	{%block content%}
	<nav class="black darken-4">
		<ul id="nav-mobile" class="center hide-on-med-and-dow">
			<li><a>Soporte las 24 horas</a></li>
			<ul id="nav-mobile" class="right hide-on-med-and-dow">
				<li><a>Llamanos 7711548189</a></li>
			</ul>
	</nav>
	<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large red">
			<i class="large material-icons">mode_edit</i>
		</a>
		<ul>
			<li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
			<li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
			<li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
			<li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
		</ul>
	</div>

{%endblock content%}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
	 {%block scripts%} {%endblock scripts%}
</body>

</html>

main/templates/home.html
{% extends 'base.html'%} 
{% block content%}



	<div class="slider fullscreen">
	    <ul class="slides">
	      <li>
		        <img src="/media/tienda/slider/s1.jpg"> <!-- random image -->
		        <div class="caption left-align">
			          <h2 class="black-text">¡Aprende!</h2>
			          <h5 class="black-text">¡Desarrolla tus skills como developer!</h5>
		        </div>
	      </li>
	      <li>
		        <img src="/media/tienda/slider/s1.jpg"> <!-- random image -->
		        <div class="caption left-align">
			          <h2 class="white-text">¡Crear!</h2>
			          <h5 class="white-text">Es lo de hoy</h5>
		        </div>
		  </li>
		  <li>
			   	 <img src="/media/tienda/slider/st.jpg"> <!-- random image -->
		      	 <div class="caption left-align">
			          <h2 class="black-text">¡Trabaja en equipo!</h2>
			          <h5 class="black-text">Comparte conocimientos</h5>
		        </div>
		  </li>
   		</ul>
	</div>			



{%endblock content%}
{%block scripts%}
	<script>
		$(document).ready(function(){
    		$('.slider').slider({full_width: true, indicators:true});

		});
	</script>
{%endblock scripts%}

orders/templates/orders/create.html
{%extends 'base.html'%} {%block titulo%} {%endblock titulo%} {%block content%}

<div id="wrapper" class="center">
    <br></br>
    <h3>Confirmacion de Orden</h3>

    <ul>
        {%for item in cart%}
        <li>
            {{item.quantity}} X {{item.producto.name}}
            <span>${{item.precio_total}}</span>
        </li>
        {%endfor%}
    </ul>
    <p>
        Total: $ {{cart.get_precio_total}}
    </p>
    <form action="." method="post" class="formulario_orden">
        {%csrf_token%} {{form.as_p}}
        <input type="submit" value="Pagar">
    </form>
</div>
{%endblock content%}

orders/templates/orders/thanks.html
{%extends 'base.html'%} {%block content%}

<h1>Gracias por darnos tu dinero</h1>
<a href="{%url 'tienda:tienda'%}">Volver</a> {%endblock content%}

payment/templates/payment/canceled.html
{%extends 'base.html'%} {%block titulo%}Pago cancelado{%endblock titulo%} {%block content%}
<section class="container">

    <h3 class="center">Tu pago no ha podido procesarse</h3>

</section>

{%endblock content%}

payment/templates/payment/done.html
{%extends 'base.html'%} {%block titulo%}Pagado usando PayPal{%endblock titulo%} {%block content%}
<section class="container">
    <h3>Tu pago ha sido recibido</h3>
</section>

{%endblock content%}

payment/templates/payment/process.html
{%extends 'base.html'%} {%block titulo%}Pagar usando PayPal{%endblock titulo%} {%block content%}
<div id="wrapper">
<br></br>
<section class="container">

    <h4>Selecciona tu forma de pago:</h4>
    <div class="divider"></div>
    <p>
        {{form.render}}
    </p>

</section>
</div>
{%endblock content%}

tienda/templates/tienda/detalle.html
{% extends 'base.html'%}{%block titulo%}{{producto.nombre}}{%endblock titulo%}{% block content%}
<div id="wrapper">
	<br></br>
	<div class="product-images"><a><img src="/media/{{producto.imagen}}" height="175"></a></div>
	<h5>{{producto.nombre}}</h5>
	<h4> $ {{producto.precio}}</h4>
	<form action="{%url 'cart:cart_add' producto.id%}" method="post">
		{%csrf_token%}{{form.as_p}}
		<input type="submit" value="Agregar al Carrito"></input>
	</form>
</div>
{% endblock content%}

tienda/templates/tienda/lista.html
{% extends 'base.html'%}{%block titulo%}Tienda{%endblock titulo%} {% block content%}

<div id="wrapper">
	<br></br>
	<h1 class="center">Articulos en venta</h1> {%for producto in productos%}
	<div class="tabla"  align="center">
		<a href="{%url 'tienda:detalle' producto.id%}">
			<h2><img src="/media/{{producto.imagen}}" height="150" width="205"></h2>
			<h4> $ {{producto.precio}}</h4>
			<h5>{{producto.nombre}}</h5>
		</a>
		<form action="{%url 'tienda:detalle' producto.id%}">
			{%csrf_token%} {{form.as_p}}
			<input type="submit" value="Detalle Producto"></input>
		</form>
	</div>
	{%empty%}
	<h2>No hay productos para mostrar</h2> {%endfor%}
</div>
{% endblock content%}